package core

func init() {
	glc.progMan.Reset()
	rs := &glc.progMan.RawSources
	rs.Fragment["rt_quad"] = "#line 1\nin vec2 var_Tex0;\n\nuniform sampler2D uni_Tex0;\n\nout vec3 out_Color;\n\n#line 1\n#ifdef FX_Grayscale\nvoid fx_Grayscale (inout vec3 vCol) {\n\tvCol.rgb = vec3((vCol.r * 0.3) + (vCol.g * 0.59) + (vCol.b * 0.11));\n}\n#endif\n\n#ifdef FX_RedTest\nvoid fx_RedTest (inout vec3 vCol) {\n\tvCol.r = 1;\n}\n#endif\n\nvoid fx_Tex0 (inout vec3 vCol) {\n\tvCol = texture(uni_Tex0, var_Tex0).rgb;\n}\n\nvoid fx_Main (inout vec3 vCol) {\n\tfx_Tex0(vCol);\n\n#ifdef FX_Grayscale\n\tfx_Grayscale(vCol);\n#endif\n\n#ifdef FX_RedTest\n\tfx_RedTest(vCol);\n#endif\n}\n\n#line 7\n\nvoid main() {\n\tfx_Main(out_Color);\n}\n"
	rs.Fragment["rt_unlit"] = "#line 1\nin vec2 var_Tex0;\n\nuniform sampler2D uni_Tex0;\n\nout vec3 out_Color;\n\n#line 1\n#ifdef FX_Grayscale\nvoid fx_Grayscale (inout vec3 vCol) {\n\tvCol.rgb = vec3((vCol.r * 0.3) + (vCol.g * 0.59) + (vCol.b * 0.11));\n}\n#endif\n\n#ifdef FX_RedTest\nvoid fx_RedTest (inout vec3 vCol) {\n\tvCol.r = 1;\n}\n#endif\n\nvoid fx_Tex0 (inout vec3 vCol) {\n\tvCol = texture(uni_Tex0, var_Tex0).rgb;\n}\n\nvoid fx_Main (inout vec3 vCol) {\n\tfx_Tex0(vCol);\n\n#ifdef FX_Grayscale\n\tfx_Grayscale(vCol);\n#endif\n\n#ifdef FX_RedTest\n\tfx_RedTest(vCol);\n#endif\n}\n\n#line 7\n\nvoid main () {\n\tfx_Main(out_Color);\n}\n"
	rs.Vertex["rt_quad"] = "#line 1\nout vec2 var_Tex0;\n\n#define VX_Quad 1\n\n#line 1\n#if defined(VX_Uni_Matrix) && defined(VX_Att_Pos)\nvoid vx_Pos_Matrix (inout vec4 vPos) {\n\tvPos = uni_VertexMatrix * vec4(att_Pos, 1.0);\n}\n#endif\n\n#ifdef VX_Att_TexCoord\nvoid vx_TexCoord_Attr (inout vec2 vTexCoord) {\n\tvTexCoord = att_Tex0;\n}\n#endif\n\n#ifdef VX_Quad\nvoid vx_Pos_Quad (inout vec4 vPos) {\n\tconst float extent = 3;\n\tconst vec2 pos[3] = vec2[](vec2(-1, -1), vec2(extent, -1), vec2(-1, extent));\n\tvPos = vec4(pos[gl_VertexID], 0, 1);\n}\n\nvoid vx_TexCoord_Quad (inout vec2 vTexCoord) {\n\tconst float extent = 3;\n\tconst vec2 vTex[3] = vec2[](vec2(0, 0), vec2(extent - 1, 0), vec2(0, extent - 1));\n\tvTexCoord = vTex[gl_VertexID];\n}\n#endif\n\nvoid vx_Pos_Main (inout vec4 vPos) {\n#if defined(VX_Uni_Matrix) && defined(VX_Att_Pos)\n\tvx_Pos_Matrix(vPos);\n#endif\n\n#ifdef VX_Quad\n\tvx_Pos_Quad(vPos);\n#endif\n}\n\nvoid vx_TexCoord_Main (inout vec2 vTex) {\n#ifdef VX_Att_TexCoord\n\tvx_TexCoord_Attr(vTex);\n#endif\n\n#ifdef VX_Quad\n\tvx_TexCoord_Quad(vTex);\n#endif\n}\n\n#line 5\n\nvoid main () {\n\tvx_Pos_Main(gl_Position);\n\tvx_TexCoord_Main(var_Tex0);\n}\n"
	rs.Vertex["rt_unlit"] = "#line 1\nin vec3 att_Pos;\nin vec2 att_Tex0;\n\nuniform mat4 uni_VertexMatrix;\n\nout vec2 var_Tex0;\n\n#define VX_Uni_Matrix 1\n#define VX_Att_Pos 1\n#define VX_Att_TexCoord 1\n\n#line 1\n#if defined(VX_Uni_Matrix) && defined(VX_Att_Pos)\nvoid vx_Pos_Matrix (inout vec4 vPos) {\n\tvPos = uni_VertexMatrix * vec4(att_Pos, 1.0);\n}\n#endif\n\n#ifdef VX_Att_TexCoord\nvoid vx_TexCoord_Attr (inout vec2 vTexCoord) {\n\tvTexCoord = att_Tex0;\n}\n#endif\n\n#ifdef VX_Quad\nvoid vx_Pos_Quad (inout vec4 vPos) {\n\tconst float extent = 3;\n\tconst vec2 pos[3] = vec2[](vec2(-1, -1), vec2(extent, -1), vec2(-1, extent));\n\tvPos = vec4(pos[gl_VertexID], 0, 1);\n}\n\nvoid vx_TexCoord_Quad (inout vec2 vTexCoord) {\n\tconst float extent = 3;\n\tconst vec2 vTex[3] = vec2[](vec2(0, 0), vec2(extent - 1, 0), vec2(0, extent - 1));\n\tvTexCoord = vTex[gl_VertexID];\n}\n#endif\n\nvoid vx_Pos_Main (inout vec4 vPos) {\n#if defined(VX_Uni_Matrix) && defined(VX_Att_Pos)\n\tvx_Pos_Matrix(vPos);\n#endif\n\n#ifdef VX_Quad\n\tvx_Pos_Quad(vPos);\n#endif\n}\n\nvoid vx_TexCoord_Main (inout vec2 vTex) {\n#ifdef VX_Att_TexCoord\n\tvx_TexCoord_Attr(vTex);\n#endif\n\n#ifdef VX_Quad\n\tvx_TexCoord_Quad(vTex);\n#endif\n}\n\n#line 12\n\nvoid main () {\n\tvx_Pos_Main(gl_Position);\n\tvx_TexCoord_Main(var_Tex0);\n}\n"
	glc.progMan.Names = []string{"rt_quad", "rt_unlit"}
}
